jobs:
  test:
    docker:
      - image: 'circleci/node:14.5-browsers'
    steps:
      - checkout
      - run: node test/newTest1.js
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test