version: 2.1
jobs:
  test:
    - image: cimg/ruby:2.7.1-node-browsers
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test

workflows:
  node-tests:
    jobs:
      - node/test
