version: 2.1
orbs:
  node: 'circleci/node@2.0.0'
jobs:
  test:
    docker:
      - image: 'circleci/node:14.5-browsers'
    steps:
      - checkout
      - node/install-packages
      - run: node test/buttonTest.js
  old-test:
    docker:
      - image: 'circleci/node:14.5-browsers'
    steps:
      - checkout
      - run: node test/newTest1.js
workflows:
  test_my_app:
    jobs:
      - test