version: 2.1
orbs:
  node: 'circleci/node@2.0.0'
  heroku: circleci/heroku@0.0.10
jobs:
  test:
    docker:
      - image: 'circleci/node:14.5-browsers'
    steps:
      - checkout
      - node/install-packages
      - run: node test/buttonTest.js
workflows:
  test_my_app:
    jobs:
      - test
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git